version: '3'

services:
  db:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: Racatapulfuf1?
      MYSQL_DATABASE: data_db
      MYSQL_USER: admin_db
      MYSQL_PASSWORD: nfsvrleRE653]%ifsd
    command: "--innodb_use_native_aio=0"
    volumes:
      - ./mysql_data:/var/lib/mysql
    ports:
      - "9906:3306"
  web:
    image: php:7.2.2-apache
    container_name: php_web
    depends_on:
      - db
    volumes:
      - ./php/:/var/www/html/
    ports:
      - "8100:80"
    stdin_open: true
    tty: true
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    depends_on:
    - db
    external_links:
    - db:mysql
    ports:
    - "9191:80"
    environment:
      MYSQL_USER: admin_db
      MYSQL_PASSWORD: nfsvrleRE653]%ifsd
      MYSQL_ROOT_PASSWORD: Racatapulfuf1?
      PMA_HOST: db